### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by lucaplayground** [666jfox777/aws-waf-rate-limiting-basic#1]
Hi there, 

I'm Yang, a student study in New Zealand. I'm writing for a confusion about this code.  Actually, I found your post last week and followed it step by step. But when I tried to run the lambda function,  it always ended at the stage "update WAF status". The error information showed "Exception: An error occurred (validationException) when calling the updateIPset operation: Update failed, invalid CIDR block: cannot parse 210.7.37.2 as a CIDR." It seems like the function cannot find CIDR of the IP address that need to be blocked. I am wondering if it came from my fault operation. But could you please check the source code  of the lambda function if possible? Looking forward to your reply. Cheers,
![image](https://cloud.githubusercontent.com/assets/20857225/20689738/caab3648-b62b-11e6-8660-219153caf52b.png)

**Comment by 666jfox777** [comment]
Hey! Thanks for reaching out!

It's been a while since I looked at this, but I think the error is related to the CIDR you're submitting - "210.7.37.2" is not a CIDR - it's an IP address. If you submit it as "210.7.37.2/32" it should process successfully.

It's probably useful to check the IP address being submitted and convert it to a /32 if one isn't provided. I'll add that in and fix the dead link references as well.

**Comment by lucaplayground** [comment]
Hi Justin,

Thanks for your reply.

My understanding is that this lambda function can extract the IP address from access logs generated by Cloudfront. And if an IP address makes more requests than the defined threshold, lambda will automatically add it to the WAF block list. Am I right? For better practice, I changed 'IP_REQUEST_BLOCKCOUNT' from 100 to 2.  And I put a sample access log into the S3 bucket to trigger this function. But the problem is that this function can capture the IP address not the CIDR, in particular, like '210.7.37.2', which cannot be added into WAF. Because WAF only support CIDR. That is my confusion.
